# Generated by Django 5.0.6 on 2026-04-21 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScraperConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(max_length=20, unique=True, verbose_name="Sumber"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif?")),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=360, verbose_name="Interval Scraping (menit)"
                    ),
                ),
                (
                    "search_keywords",
                    models.JSONField(default=list, verbose_name="Keyword Pencarian"),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Maksimal Halaman"
                    ),
                ),
                (
                    "request_delay_seconds",
                    models.FloatField(
                        default=2.0, verbose_name="Delay Antar Request (detik)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Konfigurasi Scraper",
                "verbose_name_plural": "Konfigurasi Scraper",
            },
        ),
    ]
