# Generated by Django 5.0.6 on 2026-04-21 06:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nama Perusahaan"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versi URL-friendly dari nama perusahaan. Contoh: pt-maju-jaya",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="URL Logo"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Website Perusahaan"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: Teknologi, Perbankan, E-Commerce",
                        max_length=100,
                        verbose_name="Industri",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lokasi Perusahaan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Perusahaan",
                "verbose_name_plural": "Perusahaan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("jobstreet", "Jobstreet"), ("glints", "Glints")],
                        max_length=20,
                        verbose_name="Sumber",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Sedang Berjalan"),
                            ("success", "Berhasil"),
                            ("failed", "Gagal"),
                            ("partial", "Sebagian Berhasil"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status Run",
                    ),
                ),
                (
                    "total_found",
                    models.IntegerField(default=0, verbose_name="Total Ditemukan"),
                ),
                (
                    "total_saved",
                    models.IntegerField(default=0, verbose_name="Total Disimpan"),
                ),
                (
                    "total_duplicate",
                    models.IntegerField(default=0, verbose_name="Total Duplikat"),
                ),
                (
                    "total_rejected",
                    models.IntegerField(default=0, verbose_name="Total Ditolak"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Pesan Error"),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log Scraping",
                "verbose_name_plural": "Log Scraping",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Contoh: Junior Web Developer Intern",
                        max_length=255,
                        verbose_name="Judul Lowongan",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=300, unique=True, verbose_name="Slug URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Deskripsi Pekerjaan"),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Persyaratan"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Lokasi"),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("unknown", "Tidak Diketahui"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Tipe Kerja",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("d3", "D3"),
                            ("d4", "D4"),
                            ("s1", "S1"),
                            ("all", "Semua Jenjang"),
                            ("unknown", "Tidak Diketahui"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Jenjang Pendidikan",
                    ),
                ),
                (
                    "relevant_majors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Daftar jurusan yang relevan dengan lowongan ini",
                        verbose_name="Jurusan Relevan",
                    ),
                ),
                (
                    "salary_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Gaji Minimum (Rp)"
                    ),
                ),
                (
                    "salary_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Gaji Maksimum (Rp)"
                    ),
                ),
                (
                    "is_salary_visible",
                    models.BooleanField(
                        default=False, verbose_name="Gaji Ditampilkan?"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("jobstreet", "Jobstreet"), ("glints", "Glints")],
                        max_length=20,
                        verbose_name="Sumber",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL asli lowongan di Jobstreet/Glints",
                        max_length=500,
                        unique=True,
                        verbose_name="URL Sumber",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="ID lowongan di platform asalnya",
                        max_length=100,
                        verbose_name="ID di Sumber",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("active", "Aktif"),
                            ("expired", "Kadaluarsa"),
                            ("rejected", "Ditolak"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Diisi kalau status = rejected",
                        verbose_name="Alasan Penolakan",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Posting"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Batas Pendaftaran"
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Tanggal Di-scrape",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Dilihat"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="internships.company",
                        verbose_name="Perusahaan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lowongan Magang",
                "verbose_name_plural": "Lowongan Magang",
                "ordering": ["-posted_at", "-view_count"],
                "indexes": [
                    models.Index(
                        fields=["status", "source"],
                        name="internships_status_a80aff_idx",
                    ),
                    models.Index(
                        fields=["status", "posted_at"],
                        name="internships_status_460913_idx",
                    ),
                    models.Index(
                        fields=["deadline"], name="internships_deadlin_509b56_idx"
                    ),
                ],
            },
        ),
    ]
