# Generated by Django 5.0.6 on 2026-04-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internship",
            name="source",
            field=models.CharField(
                choices=[("glints", "Glints"), ("indeed", "Indeed")],
                max_length=20,
                verbose_name="Sumber",
            ),
        ),
        migrations.AlterField(
            model_name="scrapinglog",
            name="source",
            field=models.CharField(
                choices=[("glints", "Glints"), ("indeed", "Indeed")],
                max_length=20,
                verbose_name="Sumber",
            ),
        ),
    ]
